# Generated by Django 2.2.4 on 2020-04-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_details',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('booking_date', models.DateField()),
                ('cin_time', models.TimeField()),
                ('cout_time', models.TimeField()),
                ('place_choice', models.CharField(max_length=20)),
            ],
        ),
    ]
