# Generated by Django 3.0.3 on 2020-02-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel_details',
            old_name='before_date',
            new_name='before_days',
        ),
        migrations.AlterField(
            model_name='hotel_details',
            name='hotel_location',
            field=models.TextField(),
        ),
    ]
