# Generated by Django 3.0.3 on 2020-03-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managerapp', '0002_auto_20200228_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_details',
            name='min_slot',
            field=models.IntegerField(default=True),
        ),
    ]
