# Generated by Django 3.0.3 on 2020-02-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user_model',
            name='contact_no',
            field=models.IntegerField(default=0),
        ),
    ]
