# Generated by Django 3.0.3 on 2020-02-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_auto_20200227_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user_model',
            name='contact_no',
            field=models.IntegerField(default=True),
        ),
    ]
